"""MCP server for sending emails and financial reports to configured groups."""

import os
import sys
import smtplib
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from pathlib import Path

_project_root = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
if _project_root not in sys.path:
    sys.path.insert(0, _project_root)

from dotenv import load_dotenv
load_dotenv()

import yaml
from mcp.server.fastmcp import FastMCP

mcp = FastMCP("email-agent")

_CONFIG_PATH = Path(_project_root) / "config" / "email_groups.yaml"


def _load_config() -> dict:
    if _CONFIG_PATH.exists():
        with open(_CONFIG_PATH) as f:
            return yaml.safe_load(f) or {}
    return {}


def _smtp_send(recipients: list[str], subject: str, body: str) -> str:
    host = os.getenv("SMTP_HOST", "smtp.gmail.com")
    port = int(os.getenv("SMTP_PORT", 587))
    user = os.getenv("SMTP_USER", "")
    password = os.getenv("SMTP_PASSWORD", "")

    if not user or not password:
        return (
            "Email not configured. Add SMTP_USER and SMTP_PASSWORD to your .env file.\n"
            "For Gmail: create an App Password at myaccount.google.com/security."
        )

    msg = MIMEMultipart("alternative")
    msg["Subject"] = subject
    msg["From"] = user
    msg["To"] = ", ".join(recipients)
    msg.attach(MIMEText(body, "plain", "utf-8"))

    try:
        with smtplib.SMTP(host, port, timeout=10) as server:
            server.ehlo()
            server.starttls()
            server.login(user, password)
            server.sendmail(user, recipients, msg.as_string())
        return f"Email sent successfully to: {', '.join(recipients)}"
    except smtplib.SMTPAuthenticationError:
        return "SMTP authentication failed. Check SMTP_USER and SMTP_PASSWORD in .env."
    except Exception as exc:
        return f"Failed to send email: {exc}"


@mcp.tool()
def list_email_groups() -> str:
    """List all configured email groups and their members."""
    config = _load_config()
    groups = config.get("groups", {})
    if not groups:
        return "No email groups configured. Run the app setup or edit config/email_groups.yaml."
    lines = ["=== Email Groups ==="]
    for name, members in groups.items():
        lines.append(f"  {name}: {', '.join(members)}")
    return "\n".join(lines)


@mcp.tool()
def send_email(recipients: list[str], subject: str, body: str) -> str:
    """Send a plain-text email directly to a list of email addresses."""
    return _smtp_send(recipients, subject, body)


@mcp.tool()
def send_to_group(group_name: str, subject: str, body: str) -> str:
    """Send an email to a named group defined in config/email_groups.yaml."""
    config = _load_config()
    groups = config.get("groups", {})
    if group_name not in groups:
        available = list(groups.keys()) or ["(none configured)"]
        return f"Group '{group_name}' not found. Available groups: {', '.join(available)}"
    return _smtp_send(groups[group_name], subject, body)


@mcp.tool()
def send_financial_report(group_name: str, company_name: str, report_content: str) -> str:
    """Format and send a complete financial analysis report to an email group."""
    subject = f"[Financial Analysis] {company_name}"
    separator = "=" * 56
    body = (
        f"FINANCIAL ANALYSIS REPORT\n{separator}\n"
        f"Company: {company_name}\n{separator}\n\n"
        f"{report_content}\n\n{separator}\n"
        f"Generated by Financial Investment Coach\n"
    )
    return send_to_group(group_name, subject, body)


@mcp.tool()
def send_market_alert(group_name: str, ticker: str, alert_message: str) -> str:
    """Send an urgent market alert or price notification to an email group."""
    subject = f"[MARKET ALERT] {ticker.upper()}"
    body = f"MARKET ALERT — {ticker.upper()}\n\n{alert_message}\n\n— Financial Investment Coach"
    return send_to_group(group_name, subject, body)


@mcp.tool()
def send_trade_confirmation(
    ticker: str,
    qty: float,
    side: str,
    estimated_price: float,
    portfolio_value: float,
) -> str:
    """Send a paper trade confirmation email to the 'me' group after a simulated order."""
    subject = f"[Paper Trade] {side.upper()} {qty} {ticker.upper()}"
    separator = "=" * 50
    body = (
        f"PAPER TRADE CONFIRMATION\n{separator}\n"
        f"  Action:          {side.upper()}\n"
        f"  Symbol:          {ticker.upper()}\n"
        f"  Shares:          {qty}\n"
        f"  Estimated Price: ${estimated_price:,.2f}\n"
        f"  Estimated Total: ${qty * estimated_price:,.2f}\n"
        f"  Portfolio Value: ${portfolio_value:,.2f}\n"
        f"{separator}\n\n"
        f"⚠️  PAPER TRADING ONLY — No real money was used.\n"
        f"This is a simulated order for practice purposes.\n\n"
        f"— Financial Investment Coach"
    )
    return send_to_group("me", subject, body)


@mcp.tool()
def send_weekly_coach_report(
    week_summary: str,
    market_update: str,
    portfolio_summary: str,
    opportunities: str,
) -> str:
    """
    Format and send a beginner-friendly weekly coach report to the 'weekly' email group.
    week_summary: documents analyzed and key findings this week
    market_update: performance of tracked tickers with arrows
    portfolio_summary: paper portfolio P&L summary
    opportunities: 3 investment opportunities spotted by the agents
    """
    from datetime import date
    today = date.today().strftime("%B %d, %Y")
    separator = "=" * 56

    body = (
        f"YOUR WEEKLY FINANCIAL COACH REPORT\n"
        f"Week of {today}\n"
        f"{separator}\n\n"
        f"THIS WEEK IN REVIEW\n"
        f"{'-' * 30}\n"
        f"{week_summary}\n\n"
        f"MARKET UPDATE\n"
        f"{'-' * 30}\n"
        f"{market_update}\n\n"
        f"YOUR PAPER PORTFOLIO\n"
        f"{'-' * 30}\n"
        f"{portfolio_summary}\n\n"
        f"3 OPPORTUNITIES TO WATCH\n"
        f"{'-' * 30}\n"
        f"{opportunities}\n\n"
        f"{separator}\n"
        f"Keep learning, keep growing. You're doing great!\n"
        f"— Your Financial Coach (powered by Claude + MCP)\n"
    )
    return send_to_group("weekly", f"[Weekly Coach] Your Financial Update — {today}", body)


if __name__ == "__main__":
    mcp.run()
